trigger:
  branches:
    include:
      - main

stages:
  - stage: DeployApp
    displayName: "Deploy Application Code via Ansible"
    jobs:
      - job: App_Deployment
        displayName: "Run Ansible Playbook to Deploy App"
        pool:
          name: "linux-hosted-agent"

        steps:
          # Update system and fix Microsoft repo key conflict
          - script: |
              sudo rm -f /etc/apt/keyrings/microsoft.gpg
              sudo apt update -y
              sudo apt install -y ansible
            displayName: "Install Ansible Cleanly"

          - task: DownloadSecureFile@1
            name: download_ssh_key
            inputs:
              secureFile: "id_ed25519"

          - script: |
              mkdir -p ~/.ssh
              cp $(download_ssh_key.secureFilePath) ~/.ssh/id_ed25519
              chmod 600 ~/.ssh/id_ed25519
              echo "StrictHostKeyChecking no" > ~/.ssh/config
            displayName: "Setup SSH Private Key"

          - script: |
              cd ansible
              ansible-playbook -i inventory.ini site.yml --ssh-extra-args "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
            displayName: "Run Ansible Playbook"
            env:
              ANSIBLE_HOST_KEY_CHECKING: "False"

